### ISSUE TITLE
Component scaffold should contain README file

### ISSUE THREAD

**Issue by ughitsaaron** [nymag/generator-clay#35]
Component scaffold should contain a `README.md` for a component description

**Comment by yoshokatana** [comment]
:+1: good idea

**Comment by yoshokatana** [comment]
Looks like it exists for npm components, but not internal. Add some logic around here? https://github.com/nymag/generator-clay/blob/master/generators/component/index.js#L242

**Comment by yoshokatana** [comment]
Possibly something like this?

```markdown
# <%= folderName %>

A component for [Clay](https://github.com/nymag/amphora/wiki#clay-is-divided-into-components).

## Usage

This component will be automatically recognized by `amphora`.

To include it, create an instance of it and add a reference to a component list.
```
